### ISSUE TITLE
[Regression in 4.1.2] Property 'files' or 'body' does not exist on type 'Request'

### ISSUE THREAD

**Issue by Cocophotos** [dlau/koa-body#176]
## Problem/Feature Request Summary
When upgrading from 4.1.1 to 4.1.2, I've got this error : "Property 'files' or 'body' does not exist on type 'Request'".
## Environment Information

  * koa-body: 4.1.2
  * Koa: 2.11.0
  * Node.js: Latest LTS (12)

## Current Behavior
Compiling with tsc I've got the following error : "Property 'files' or 'body' does not exist on type 'Request'". It didn't happen with the v4.1.1, everything was working perfectly fine.

## Steps to Reproduce

Install the 4.1.2 version of Koa-body since nothing else changed.

## Expected Behavior
tsc should compile the file correctly

## Possible Solution
I've no idea, possibly linked with #175 

## Context (Environment)

Typescript 3.9.2

**Comment by Eusen** [comment]
@MarkHerhold I think this issue is due to the PR submitted by me.
After my research, I found a solution. Just add `{ "compilerOptions": { "esModuleInterop": true } }` to `tsconfig.json`, then we can compile `declare module "koa" { }` pass through.

I'm very sorry for that...

**Comment by Eusen** [comment]
Duplicate of #173

**Comment by Cocophotos** [comment]
No worries at all! As long as a fix exists and is submitted quickly, we all can manage. :)

**Comment by albehrens** [comment]
Thank you for pointing this out. This broke our builds.

**Comment by Cocophotos** [comment]
@Eusen I've checked and we already have esModuleInterop: true in all our builds, so I don't think this is the fix we need. I guess #175 is still the way to go. Others have the same behaviour? @albehrens ?

Thanks

**Comment by albehrens** [comment]
Yes, we experienced the same behaviour as described in this ticket. We updated our repositories to use the fixed version of 4.1.1.

**Comment by MarkHerhold** [comment]
Shoot. Sorry guys :(
I will get this merged and re-released.

@Cocophotos I mentioned in the prior PR that we really need TS-based package integration tests (to prevent problems like this). Could you provide a minimal example where this breaks?

**Comment by Cocophotos** [comment]
@MarkHerhold Sure thing! I'll do that tonight after work.

Best

**Comment by MarkHerhold** [comment]
Reverted that PR and published as 4.1.3

**Comment by Cocophotos** [comment]
@MarkHerhold Took me less time than expected, so it's done. I've attached the files (I can create a Github repo if needed).

If you run npm run build, you'll end up with that error:
![screenshot-2020-05-19-16-28-27](https://user-images.githubusercontent.com/1861291/82339117-f9795a00-99ed-11ea-9f24-17152962faf5.png)

And you can see the esModuleInterop: true in the tsconfig.json
![screenshot-2020-05-19-16-28-42](https://user-images.githubusercontent.com/1861291/82339158-05fdb280-99ee-11ea-8fe9-d2d3ca42b95c.png)

Hope it helps.
[test-koa-body.zip](https://github.com/dlau/koa-body/files/4651102/test-koa-body.zip)
